#! /usr/bin/python

import os
import sys
import shutil
FLYDB_PATH = '/media/imager/DataExternal/FlyDB'
BAG_PATH = '/home/imager/bagfiles'

def main():
	# get list of all bag files saved in default location -- take the most recent one
	bag_filenames = filter(lambda x: x.endswith(".bag"), os.listdir(BAG_PATH))
	bag_filepaths = [os.path.join(BAG_PATH, fn) for fn in bag_filenames]
	bag_filepaths.sort(key=os.path.getmtime)
	newest_bag = bag_filepaths[-1]

	# get list of folders in flyDB
	flydb_folders = [d for d in os.listdir(FLYDB_PATH) if os.path.isdir(os.path.join(FLYDB_PATH, d))]
	flydb_folders.sort()
	last_fly = flydb_folders[-1]
	last_fn = int(last_fly.split('Fly')[1])
	next_fly = os.path.join(FLYDB_PATH,'Fly%04d'%(last_fn+1))

	# copy bag file to FlyDB folder
	print 'copying %s \n to %s'%(newest_bag,next_fly)
	os.mkdir(next_fly)
	shutil.copy2(newest_bag,next_fly)

if __name__ == '__main__':
	main()
